#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2016 OpenWrt.org

START=990

CONF=/etc/frps.ini
PIDFILE=/tmp/frps.pid

getpid(){
        echo `pidof frpc`
}

start(){
        if [ ! -f "$PIDFILE" ]; then
                /usr/bin/frps -c $CONF >/dev/null 2>&1 &
                sleep 3s
                pid=`pidof frpc`
                echo $pid > $PIDFILE
                echo "Frpc has started."
        else
                echo "Frpc has already started."
        fi
}

stop(){
        if [ ! -f "$PIDFILE" ]; then
                echo "Frpc is not running."
        else
                pid=`cat $PIDFILE`
                kill $pid
                rm -f $PIDFILE
                echo "Frpc has stopped."
        fi
        rm -f $PIDFILE
}

restart(){
        stop
        sleep 3 
        start
        echo "Frpc has restarted."
}

